- name: install java
  ansible.builtin.import_role:
    name: common   
    tasks_from: mavan   

- name: setup app
  ansible.builtin.import_role:
    name: common   
    tasks_from: app-setup 

- name: install dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: rename dependencies
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app

- name: setup app
  ansible.builtin.import_role:
    name: common   
    tasks_from: systemd-setup 

- name: load data
  ansible.builtin.import_role:
    name: common   
    tasks_from: load-mysql-schema  