# import role(nodejs) to catalogue
- name: Run tasks/other.yaml instead of 'main'
  ansible.builtin.import_role:
    name: common   
    tasks_from: nodejs        

- name: setup app
  ansible.builtin.import_role:
    name: common   
    tasks_from: app-setup 

- name: install dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: setup app
  ansible.builtin.import_role:
    name: common   
    tasks_from: systemd-setup 

- name: load data
  ansible.builtin.import_role:
    name: common   
    tasks_from: load-mongo-schema     